name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: echo "Checking out the repository..."
        shell: bash
        # Using actions/checkout to ensure the repository is checked out
        uses: actions/checkout@v2
  
  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Goodbye world
        run: echo "Goodbye world!"
        shell: bash
        # This step simply prints "Goodbye world!" to the console 