name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # This step checks out the repository so that the workflow can access its contents
      - name: Checkout repository
        run: echo "Checking out the repository..."
        shell: bash
  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Goodbye world
        run: echo "Goodbye world!"
        shell: bash
        # This step simply prints "Goodbye world!" to the console 